---

- hosts: webservers
  become: yes

  tasks:
 
  - name: Installing nginx
    apt:
      name: nginx
      state: present

  - name: install php files from ppa repo      
    apt_repository:      
      repo: 'ppa:ondrej/php'

  - name: Installing php-fpm
    apt:
      name: php7.4-fpm
      state: present

  - name: upgrade packages
    apt:
      update_cache: yes
      upgrade: dist
      force_apt_get: yes
    notify:
      - run nginx
      - run php7.4-fpm

  - name: Removes "nginx.conf" site at etc/nginx/
    file:
       path: "/etc/nginx/nginx.conf"
       state: absent
 
  - name: Sets nginx.conf file at etc/nginx/
    template:
       src: "./nginx.conf"
       dest: "/etc/nginx/nginx.conf"
    notify:
    - restart php7.4-fpm
    - restart nginx



  - name: Removing existing default_file from sites-enabled
    file:
       path: "/etc/nginx/sites-enabled/default"
       state: absent
    notify:
    - restart nginx

  - name: inserting my file int the sites-available
    template:
       src: "./default"
       dest: "/etc/nginx/sites-available/default1"

  - name: linking default to sites-enabled
    file:
       src: "/etc/nginx/sites-available/default1"
       dest: "/etc/nginx/sites-enabled/default1"
       state: link
    notify:
    - restart nginx


  - name: placing index.php_file at /var/www/html
    template:
      src: "./index.php"
      dest: "/var/www/html/index.php"
    notify:
    - restart nginx
    - run nginx
    - restart php7.4-fpm
    - run php7.4-fpm

  handlers:

  - name: run php7.4-fpm
    service:
      name: php7.4-fpm
      state: started

  - name: run nginx
    service:
      name: nginx
      state: started

  - name: restart php7.4-fpm
    service:
      name: php7.4-fpm
      state: restarted
  - name: restart nginx
    service:
      name: nginx
      state: restarted